server:
  port: 8761

spring:
  application:
    name: eureka-discovery

security:
  basic:
    enabled: true        # 开启基于 HTTP basic 的认证
  user:
    name: ys              # 配置登录的账号
    password: ys1234      # 配置登录的密码

eureka:
  client:
    fetch-registry: false # 表示是否从 Eureka Server 获取信息,默认为 true
    register-with-eureka: false  # 表示是否将自己注册到 Eureka Server,默认为 true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ # 设置 Eureka Server 交互的地址
  instance:
    hostname: localhost
  server:  # 配置属性，但由于 Eureka 自我保护模式以及心跳周期长的原因，经常会遇到 Eureka Server 不剔除已关停的节点的问题
    enable-self-preservation: false # 关闭自我保护模式
    eviction-interval-timer-in-ms: 5000 # 设置心跳检测时间